#!/usr/bin/env tsx

/**
 * Codegen script: reads src/source-icons/ and generates:
 * - src/generated/icons.ts     — map of platform id → { viewBox, content, badge?, badgeDark? }
 * - src/generated/platform-ids.ts — TypeScript union type for autocomplete
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync, statSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'
import { optimize } from 'svgo'
import { extractSvgContent, extractViewBox, prefixIds } from '../src/core/svg.js'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')

const SOURCE_DIR = join(ROOT, 'src/source-icons')
const GENERATED_DIR = join(ROOT, 'src/generated')

function optimizeSvg(raw: string): string {
  const result = optimize(raw, {
    multipass: true,
    plugins: [
      {
        name: 'preset-default',
        params: {
          overrides: {
            // Keep IDs — we prefix them ourselves
            cleanupIds: false,
            // Keep viewBox
            removeViewBox: false,
          },
        },
      },
    ],
  })
  return result.data
}

function readSvgFile(path: string): string | undefined {
  if (!existsSync(path)) return undefined
  return readFileSync(path, 'utf-8')
}

function processSvg(raw: string, prefix: string): { viewBox: string; content: string } {
  const optimized = optimizeSvg(raw)
  const viewBox = extractViewBox(optimized)
  const content = prefixIds(extractSvgContent(optimized), prefix)
  return { viewBox, content }
}

function escapeForTemplate(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$')
}

function main() {
  console.log('Generating icon data...\n')

  if (!existsSync(SOURCE_DIR)) {
    console.error(`Source directory not found: ${SOURCE_DIR}`)
    process.exit(1)
  }

  mkdirSync(GENERATED_DIR, { recursive: true })

  // Discover platform directories (skip _review and hidden dirs)
  const platformIds = readdirSync(SOURCE_DIR)
    .filter((name) => {
      if (name.startsWith('_') || name.startsWith('.')) return false
      const dirPath = join(SOURCE_DIR, name)
      return statSync(dirPath).isDirectory() && existsSync(join(dirPath, 'icon.svg'))
    })
    .sort()

  const entries: string[] = []

  for (const id of platformIds) {
    const dir = join(SOURCE_DIR, id)

    try {
      // Process icon.svg (required)
      const iconRaw = readFileSync(join(dir, 'icon.svg'), 'utf-8')
      const icon = processSvg(iconRaw, id)

      // Process badge.svg (optional)
      const badgeRaw = readSvgFile(join(dir, 'badge.svg'))
      let badge: { viewBox: string; content: string } | undefined
      if (badgeRaw) {
        badge = processSvg(badgeRaw, `${id}-badge`)
      }

      // Process badge-dark.svg (optional)
      const badgeDarkRaw = readSvgFile(join(dir, 'badge-dark.svg'))
      let badgeDark: { viewBox: string; content: string } | undefined
      if (badgeDarkRaw) {
        badgeDark = processSvg(badgeDarkRaw, `${id}-badge-dark`)
      }

      let entry = `  '${id}': {\n`
      entry += `    viewBox: '${icon.viewBox}',\n`
      entry += `    content: \`${escapeForTemplate(icon.content)}\`,\n`
      if (badge) {
        entry += `    badge: \`${escapeForTemplate(badge.content)}\`,\n`
      }
      if (badgeDark) {
        entry += `    badgeDark: \`${escapeForTemplate(badgeDark.content)}\`,\n`
      }
      entry += `  }`

      entries.push(entry)
      console.log(`  ${id}`)
    } catch (e: unknown) {
      console.error(`  ${id}: ${e instanceof Error ? e.message : e}`)
    }
  }

  // Write icons.ts
  const iconsTs = `// Auto-generated by scripts/codegen.ts — do not edit
import type { IconData } from '../core/types.js'

export const iconDataMap: Record<string, IconData> = {
${entries.join(',\n')}
}
`

  writeFileSync(join(GENERATED_DIR, 'icons.ts'), iconsTs)

  // Write platform-ids.ts
  const unionType = platformIds.map((id) => `  | '${id}'`).join('\n')
  const platformIdsTs = `// Auto-generated by scripts/codegen.ts — do not edit

export type PlatformId =
${unionType}
`

  writeFileSync(join(GENERATED_DIR, 'platform-ids.ts'), platformIdsTs)

  console.log(`\n${platformIds.length} platforms generated`)
}

main()
